name: Commit specification to repository

permissions:
  id-token: write
  contents: write
  pull-requests: write

on:
  issues:
    types: [labeled]

jobs:
  commit-spec:
    if: ${{ github.event.label.name == 'specification-ready' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Determine spec name
        id: get_spec_name
        run: |
          name=$(python scripts/get_spec_file_name.py)
          echo "spec-name=$name" >> $GITHUB_OUTPUT

      - name: Configure Git Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: git checkout new branch
        run: git checkout -b ${{ steps.get_spec_name.outputs.spec-name }}

      - name: Write and commit spec file
        run: |
          echo ${{ env.ISSUE_BODY }} > "specs/${{ steps.get_spec_name.outputs.spec-name }}.md"
          git add -A
          git commit -am "Add spec file ${{ steps.get_spec_name.outputs.spec-name }}.md"
          git push origin ${{ steps.get_spec_name.outputs.spec-name }}

      - name: Create PR
        run: |
          gh pr create --title "[SPEC] ${{ steps.get_spec_name.outputs.spec-name }}.md" --body "Closes #${{ env.ISSUE_NUMBER }}" --label "specification-merge"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    env:
      ISSUE_TITLE: ${{ github.event.issue.title }}
      ISSUE_BODY: ${{ github.event.issue.body }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
